### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polytool#33]
FYI upon installation (`npm install -g polytool`... I'm using `nvm` so `sudo` wasn't necessary) and running `polytool` I immediately encountered the following error:

```
/Users/kayce/.nvm/versions/node/v4.2.3/lib/node_modules/polytool/node_modules/polylint/node_modules/hydrolysis/node_modules/babel-polyfill/lib/index.js:14
  throw new Error("only one instance of babel-polyfill is allowed");
  ^

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/kayce/.nvm/versions/node/v4.2.3/lib/node_modules/polytool/node_modules/polylint/node_modules/hydrolysis/node_modules/babel-polyfill/lib/index.js:14:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/kayce/.nvm/versions/node/v4.2.3/lib/node_modules/polytool/node_modules/polylint/node_modules/hydrolysis/index.js:12:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

It's probably just something in my environment but I'll just post my findings along the way for anyone else that gets in the same boat.

**Comment by kaycebasques** [comment]
I updated to the latest stable Node.js version (`nvm install 4.4.3 && nvm use 4.4.3`... check https://nodejs.org/en/ for the number of the latest stable version) and the issue went away. I'm getting a different issue now but I'm assuming they're not related.

**Comment by doctor-g** [comment]
I see this same error, with the following stack trace, running `polymer build` with Node.js version 6.2.1 on Linux.
```
error:   Uncaught exception: Error: only one instance of babel-polyfill is allowed
error:   Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/babel-polyfill/lib/index.js:12:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/index.js:12:1)
    at Module._compile (module.js:541:32)
```
