### ISSUE TITLE
module.js cannot find module 'command-line-commands'

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polytool#34]
On a fresh install of `npm` (v6.0.0) using `nvm` (`nvm install 6.0.0`) I encountered the following error after running `polytool help`:

```
module.js:440
    throw err;
    ^

Error: Cannot find module 'command-line-commands'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kayce/node_modules/polytool/lib/polytool.js:11:29)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

This is probably not related to `polytool` but I'll post my findings here in case anyone else encounters similar problems.

**Comment by kaycebasques** [comment]
solution: re-installing polytool  (`npm install -f polytool`) did the trick

This [SO thread](http://stackoverflow.com/questions/9023672) got me on the right path. I don't know exactly what went wrong, but I noticed that the `polytool` install process involved a lot of dependencies, so my hunch is that the install process took too long, or some dependency took too long to download, or something got corrupted. So, running the install a second time helps, because most of the dependencies are already installed or cached.
